### PR TITLE
chore: fix vscode config

### PR DESCRIPTION
**Pull request by erezrokah**
See https://github.com/netlify/cli/issues/409#issuecomment-843346116

### CODE REVIEW

**Comment by MentalGear** [comment]
Thanks, yet unfortunately, this is not working for me:

Screenshot 2021-05-19 at 15 13 22

**Comment by erezrokah** [comment]
Hi @MentalGear, I believe this is a caught exception you can ignore. You should be able to disable breakpoints for such exceptions using the option on the left pane. See [here](https://code.visualstudio.com/docs/editor/debugging) for more details

**Comment by MentalGear** [comment]
I deactivated "caught exceptions" and I can run it now, but still no stopping at breakpoints.
Did breakpoints work for you on this repo?


Screenshot 2021-05-19 at 15 47 51

Also, I tried passing a custom webpack config using netlify dev --config webpack.dev.js to deactivate optimization as described in the [netlify guide](https://github.com/netlify/netlify-lambda#--config-option).

Even though `netlify dev` seems to have a `--config` flag, it doesn't seem to support the same structure as described in the netlify functions guide.

```bash
netlify dev --config webpack.dev.js
Debugger attached.
When resolving config file /Users/Tom/Desktop/netlify-dev_debug_vs-code/webpack.dev.js:
Could not parse configuration file
Expected "#", "'", "[", "\"", "\n", "\r", [ \t], [A-Za-z0-9_\-] or end of input but "/" found.
Waiting for the debugger to disconnect...
```

webpack.dev.js
```js
module.exports = {
  mode: "development", // "production" | "development" | "none"
  // Chosen mode tells webpack to use its built-in optimizations accordingly.
  },
  devtool: "source-map", // enum
  // list of additional plugins
  optimization: false,
  /* Advanced configuration (click to show) */
  /* Advanced caching configuration (click to show) */
  /* Advanced build configuration (click to show) */
}
```

**Comment by erezrokah** [comment]
> Also, I tried passing a custom webpack config using netlify dev --config webpack.dev.js to deactivate optimization as described in the [netlify guide](https://github.com/netlify/netlify-lambda#--config-option).

The `--config` flag is for `netlify-lambda` not `netlify dev`.

For `netlify dev` the `--config` flag is not officially supported and only used internally. See https://cli.netlify.com/commands/dev for available flags.

Since you're [using `esbuild`](https://github.com/MentalGear/netlify-dev_debug_vs-code/blob/c693f958dbaab526fdfe1d5e5dadc2d61d415666/netlify.toml#L24) you'll need to debug the bundled functions.
I suggest putting a `debugger` statement [here](https://github.com/MentalGear/netlify-dev_debug_vs-code/blob/c693f958dbaab526fdfe1d5e5dadc2d61d415666/serverlessFunctions/helloServerless.js#L2) and see if that works

**Comment by MentalGear** [comment]
Thanks for your help @erezrokah (indeed I knew about --config flag, but wanted to give it a shot anyhow).
I had to add some extra fixes (see latest commits) to fix all the caught exceptions warnings and source maps work now also fine (or at least don't show warnings). I added a full guide for others as an example.
If you know a place where I could add this as an example for the netlify guide, let me know.

**Comment by erezrokah** [comment]
Hi @MentalGear this is great, how about adding a section about it here:
https://github.com/netlify/cli/blob/main/docs/functions-dev.md
https://cli.netlify.com/functions-dev

**Pull request closed without merging**
